# Generated by Django 5.1.4 on 2025-01-30 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joblist', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationmentor',
            name='essay',
            field=models.TextField(max_length=1000),
        ),
    ]
