# Generated by Django 5.1.4 on 2025-01-17 03:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('joblist', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobapply',
            old_name='qualifications',
            new_name='previousjobs',
        ),
    ]
