# Generated by Django 4.2.16 on 2024-11-27 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joblist', '0002_remove_jobapply_jobfield_joblisting_jobfield'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joblisting',
            name='jobfield',
            field=models.CharField(blank=True, choices=[('Arts', 'Arts'), ('Business', 'Business'), ('Communications', 'Communications'), ('Education', 'Education'), ('Healthcare', 'Healthcare'), ('Hospitality', 'Hospitality'), ('Information Technology', 'Information Technology'), ('Law Enforcement', 'Law Enforcement'), ('Sales and Marketing', 'Sales and Marketing'), ('Science', 'Science'), ('Transportation', 'Transportation'), ('Other', 'Other')], default='other', max_length=100, null=True),
        ),
    ]
