# Generated by Django 5.1.4 on 2025-01-31 06:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joblist', '0002_alter_applicationmentor_essay'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='mentor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='joblist.applicationmentor'),
        ),
    ]
