# Generated by Django 4.2.16 on 2024-12-17 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joblist', '0003_alter_joblisting_jobfield'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('Student', 'Student'), ('Employer', 'Employer'), ('Mentor', 'Mentor')], max_length=20),
        ),
    ]
