# Generated by Django 5.1.4 on 2025-02-04 05:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joblist', '0006_meetingevent_current_people_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetingevent',
            name='attendees',
            field=models.ManyToManyField(blank=True, related_name='joined_meetings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='meetingevent',
            name='mentor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hosted_meetings', to=settings.AUTH_USER_MODEL),
        ),
    ]
