# Generated by Django 5.1.4 on 2025-02-04 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joblist', '0007_meetingevent_attendees_alter_meetingevent_mentor'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='offers',
            field=models.ManyToManyField(blank=True, related_name='offers', to='joblist.joblisting'),
        ),
    ]
