databases:
  - name: jobviewdb
    plan: free
    databaseName: jobview
    user: postgres
    password: yourpassword

services:
  - type: web
    plan: free
    name: jobview
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "python -m gunicorn mysite.asgi:application -k uvicorn.workers.UvicornWorker"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: jobviewdb
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4